services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: billing-backend-dev
    ports:
      - "8002:8002"
    volumes:
      - .:/app  # mount local code for live reload
    environment:
      DEBUG: "True"
      SECRET_KEY: dev-secret-key-change-in-production-12345
      DJANGO_SETTINGS_MODULE: billing_service.settings.dev
      DJANGO_ENV: dev
      DATABASE_URL: postgresql://devuser:devpass@db:5432/billing_devdb
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0,billing-backend-dev
      CORS_ALLOW_ALL_ORIGINS: "True"
      PESAWAY_TEST_MODE: "true"
      # M-Pesa Sandbox Credentials
      MPESA_TEST_MODE: "true"
      MPESA_CONSUMER_KEY: "WZ6b1Y6ZjRbwNJwwQzULthXjesQR0OtsEuQh9jt7tz3CtSpG"
      MPESA_CONSUMER_SECRET: "zuVci1S1rl6An6bistz6jUo1eJ0Is8kM3IGlghGFCUpF4coKx7YtmGbAbLgvyddS"
      MPESA_SHORTCODE: "174379"
      MPESA_PASSKEY: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
      MPESA_CALLBACK_URL: "https://webhook.site/2e25a120-8db2-41ac-a98e-ab50c6f8c288"
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin123
    depends_on:
      - db
    networks:
      - billing_net
      - quidpath_network  # Shared network for inter-service communication

  db:
    image: postgres:15
    container_name: postgres_billing_dev
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: billing_devdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - billing_net

volumes:
  postgres_data:

networks:
  billing_net:
    driver: bridge
  quidpath_network:
    external: true  # This network is shared with the main backend



