services:
  db:
    image: postgres:15
    container_name: postgres_billing_prod
    restart: unless-stopped
    volumes:
      - /mnt/ebs/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - billing_network
      - quidpath_network

  backend:
    image: ${IMAGE_TAG}
    container_name: billing-backend-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:8007:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
      BILLING_SERVICE_SECRET: ${BILLING_SERVICE_SECRET}
      DJANGO_SETTINGS_MODULE: billing_service.settings.prod
      DJANGO_ENV: prod
    volumes:
      - /mnt/ebs/media:/app/media
      - /mnt/ebs/staticfiles:/app/staticfiles
    networks:
      - billing_network
      - quidpath_network

networks:
  billing_network:
    name: billing_prod_network
    driver: bridge
  quidpath_network:
    external: true
    name: tmp_quidpath_network

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ebs/postgres_data