# Generated by Django 4.2.28 on 2026-02-25 06:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corporate_id', models.UUIDField(db_index=True)),
                ('corporate_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('verification_amount', models.DecimalField(decimal_places=2, default=1.0, help_text='Verification amount in KES', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('payment_provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_receipt_number', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_receipt_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('refund_metadata', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('trial_created', models.BooleanField(default=False)),
                ('trial_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_payment_verification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=20)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('monthly_price_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.JSONField(default=dict)),
                ('max_users', models.IntegerField(default=1)),
                ('max_transactions', models.IntegerField(default=100)),
                ('max_invoices', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'unified_subscription_plans',
                'ordering': ['plan_type', 'monthly_price_kes'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending_payment', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unified_subscriptions', to='billing.subscriptionplan')),
            ],
            options={
                'db_table': 'unified_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(default='mpesa', max_length=50)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_merchant_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.unifiedsubscription')),
            ],
            options={
                'db_table': 'unified_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['plan_type', 'is_active'], name='unified_sub_plan_ty_cbbe13_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['tier', 'plan_type'], name='unified_sub_tier_2336ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('plan_type', 'tier')},
        ),
        migrations.AddIndex(
            model_name='paymentverification',
            index=models.Index(fields=['corporate_id', 'status'], name='billing_pay_corpora_b0ac98_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentverification',
            index=models.Index(fields=['payment_provider_reference'], name='billing_pay_payment_1c12b6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentverification',
            index=models.Index(fields=['status', 'created_at'], name='billing_pay_status_0b05e9_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedsubscription',
            index=models.Index(fields=['entity_id', 'status'], name='unified_sub_entity__6cf43a_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedsubscription',
            index=models.Index(fields=['subscription_type', 'status'], name='unified_sub_subscri_b35f40_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedsubscription',
            index=models.Index(fields=['status', 'end_date'], name='unified_sub_status_84152e_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedpayment',
            index=models.Index(fields=['entity_id', 'status'], name='unified_pay_entity__a2d1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedpayment',
            index=models.Index(fields=['payment_type', 'status'], name='unified_pay_payment_665beb_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedpayment',
            index=models.Index(fields=['mpesa_checkout_request_id'], name='unified_pay_mpesa_c_621461_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedpayment',
            index=models.Index(fields=['idempotency_key'], name='unified_pay_idempot_29f613_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedpayment',
            index=models.Index(fields=['status', 'created_at'], name='unified_pay_status_4e6aba_idx'),
        ),
    ]
