# Generated by Django 4.2.28 on 2026-02-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentverification_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='unifiedpayment',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='unifiedsubscription',
            name='plan',
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['plan_type', 'price_monthly'], 'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.RemoveIndex(
            model_name='plan',
            name='billing_pla_tier_fdafe0_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_merchant_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], default='organization', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], default='organization', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], default='organization', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('pending', 'Pending'), ('pending_payment', 'Pending Payment')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('plan_type', 'tier')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'status'], name='billing_pay_payment_7e816b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['mpesa_checkout_request_id'], name='billing_pay_mpesa_c_c9eaa1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['idempotency_key'], name='billing_pay_idempot_96c174_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['plan_type', 'tier', 'is_active'], name='billing_pla_plan_ty_f06627_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscription_type', 'status'], name='billing_sub_subscri_f785ea_idx'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UnifiedPayment',
        ),
        migrations.DeleteModel(
            name='UnifiedSubscription',
        ),
    ]
