# Generated by Django 4.2.29 on 2026-04-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_subscriptionplan_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='mpesa_phone',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='mobile_money_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('ussd', 'USSD'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('card', 'Card'), ('mobile_money', 'Mobile Money'), ('bank_account', 'Bank Account')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider',
            field=models.CharField(default='paystack', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('test_limited', 'Test - Limited'), ('test_full', 'Test - Full Access')], max_length=50),
        ),
    ]
